name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build and Push the Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: opencsi/tailscale
        registry: docker.io
        tags: latest,1.24.2
        dockerfile: Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push the Docker image Lan
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: opencsi/tailscale
        registry: docker.io
        tags: stable-LantoLan,1.24.2
        dockerfile: ./LantoLan/Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
